server:
  port: 8004  #端口配置
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 5
          max-interval: 20000ms
          initial-interval: 2000ms
          multiplier: 2
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: 123456
logging:
  level:
    cn.liulingfengyu.scheduledTask: debug
  file:
    path: log