server:
  port: 8004  #端口配置
spring:
  datasource: #配置数据库
    dynamic:
      primary: scheduled_task #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        scheduled_task:
          url: jdbc:mysql://127.0.0.1:3306/sa_scheduled_task_open_db?useUnicode=true&useSSL=false&characterEncoding=utf8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false
          username: root
          password: 1q@w3e4r
          hikari:
            maximum-pool-size: 20
            minimum-idle: 5
            idle-timeout: 30000
            max-lifetime: 1800000
            connection-timeout: 30000
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 5
          max-interval: 20000ms
          initial-interval: 2000ms
          multiplier: 2
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: 123456
logging:
  level:
    cn.liulingfengyu.scheduledTask: debug
  file:
    path: log
# swagger配置
knife4j:
  enable: true  #是否开启Knife4j增强模式
  setting:
    enable-after-script: false
    enable-swagger-models: false
    enable-home-custom: true
    home-custom-path: classpath:markdown/home.md
    enable-footer-custom: true
    footer-custom-content: Copyright © 2023 刘凌枫羽工作室所有
    enable-open-api: false
  documents:
    - name: 文档
      locations: classpath:markdown/custom/*
      group: default