server:
  port: 8001  #端口配置
spring:
  datasource: #配置数据库
    dynamic:
      primary: scheduled_task #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        scheduled_task:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://127.0.0.1:3306/sa_scheduled_task_open_db?useUnicode=true&useSSL=false&characterEncoding=utf8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false
          username: root
          password: 1q@w3e4r
      druid:
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
  redis: #redis参数配置
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 5
          max-interval: 20000ms
          initial-interval: 2000ms
          multiplier: 2
actuator:
  name: actuator-1 #执行器名称
  core-pool-size: 2 #调度器线程池核心线程数
logging:
  level:
    cn.liulingfengyu.actuator: debug
  file:
    path: log