spring:
  profiles:
    active: @profiles.active@
knife4j:
  enable: true  #是否开启Knife4j增强模式
  setting:
    enable-home-custom: true #启用自定义首页
    home-custom-location: classpath:markdown/home.md #首页md文件路径
    enable-footer: false #关闭默认页脚
    enable-footer-custom: true #启用自定义页脚
    footer-custom-content: Copyright © 2022 Liu Ling Feng Yu Studio #自定义页脚内容
    enable-swagger-models: true #是否显示界面中SwaggerModel功能
    swagger-model-name: Models #SwaggerModel名称
    enable-open-api: false #显示OpenAPI规范
    enable-host: false #是否启用Host
    enable-host-text: "http://192.168.168.189:8080" #HOST地址
    enable-debug: true #启用调试
  documents: #自定义文档集合，该属性是数组
    - group: 1.0.0 #所属分组
      name: 自定义文档 #类似于接口中的tag,对于自定义文档的分组
      locations: classpath:markdown/custom/* #markdown文件路径,可以是一个文件夹(classpath:markdowns/*)，也可以是单个文件(classpath:md/sign.md)

apiInfo:
  title: single-application-framework 项目接口文档 #标题
  description: single-application-framework 项目接口文档 #简介
  basePackage: com.llfy.saapp.page #扫描路径
  contact:
    name: LLFY #作者
    url: https://blog.csdn.net/qq_38036909?type=blog #联系地址
    email: 1305156911@qq.com #邮箱
  version: v1.0 #版本
