server:
  port: 9992  #端口配置
spring:
  redis: #redis参数配置
    host: 154.8.144.189
    port: 26379
    password: 1q@w3e4r
    database: 0
logging:
  level:
    com.llfy.cesea: debug  #日志级别
  file:
    path: log #日志输出路径
scheduled:
  corePoolSize: 3 #定时任务核心线程数
  callback: /scheduledExecutor/callback #消息回调地址
business:
  name: business #业务集群名称
actuator:
  name: actuator #执行器集群名称
app:
  name: cluster-2 #执行器名称
  heartbeat:
    interval: 5000 #执行器心跳检测