server:
  port: 9998  #端口配置
spring:
  datasource: #配置数据库
    dynamic:
      primary: scheduled_task #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        scheduled_task:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://154.8.144.189:23306/sa_scheduled_task_db?useUnicode=true&useSSL=false&characterEncoding=utf8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false
          username: root
          password: 1q@w3e4r
      druid: # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000 # 配置获取连接等待超时的时间
        time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        min-evictable-idle-time-millis: 300000  # 配置一个连接在池中最小生存的时间，单位是毫秒
  redis: #redis参数配置
    host: 154.8.144.189
    port: 26379
    password: 1q@w3e4r
    database: 0
logging:
  level:
    com.llfy.cesea: debug  #日志级别
  file:
    path: log #日志输出路径
scheduled:
  corePoolSize: 3 #定时任务核心线程数
  callback: http://localhost:9999/scheduledExecutor/callback,http://localhost:9998/scheduledExecutor/callback
app:
  name: cluster-2 #执行器名称
  heartbeat:
    interval: 5000 #执行器心跳检测